### PR TITLE
Added hasRequestDecorator check before calling decorateRequest

### LINKED ISSUE #88: multiple register
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We should check with `fastify.hasDecorator()` before adding the decorator.

so the user may register the plugin multiple times without issue.

Idea from: https://github.com/fastify/fastify-http-proxy/pull/205

### Motivation

_No response_

### Example

_No response_

### PR DESCRIPTION
**Pull request by sztobar**
fixes #88

#### Checklist

- [x] run `npm run test` ~and `npm run benchmark`~ _- no `npm run benchmark` in this repo_
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added _- I don't think that a change in the documentation is needed_
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — APPROVED** [review]
🚀

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — CHANGES_REQUESTED** [review]
I am a bit late, but this PR allow the conflict of
```ts
fastify.decorateRequest('urlData', 'boom')
fastify.register(fastifyUrlDate) // the error message is actually very useful in this case.
```

**Comment by Eomm** [comment]
could we log a warning in this case?

**Review by jsumners — CHANGES_REQUESTED** [review]
https://github.com/fastify/fastify-url-data/issues/88#issuecomment-986747575

**Comment by sztobar** [comment]
I understand the point of @climba03003. While the [PR ](https://github.com/fastify/fastify-http-proxy/pull/205#discussion_r762601936) example that sparked the idea behind the issue creation seemed right to me, I also believe that it should be the responsibility of libraries/plugins authors and `fastify` end-users to check if the plugin was already added or not.

@Eomm how to feel about closing this PR in that case?

**Comment by Eomm** [comment]
> how to feel about closing this PR in that case?

Yes, there is no agreement for this check and this configuration does the work: https://github.com/fastify/fastify-url-data/issues/88#issuecomment-986844174

Thanks for your help

**Pull request closed without merging**
