### PR TITLE
Add scheme for http/https servers

### PR DESCRIPTION
**Pull request by gugu**
Related to #69

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Missing the `scheme` assertion in test "parses a full URI in HTTP2"

**Comment by gugu** [comment]
done

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by Eomm — APPROVED** [review]

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
